[theme]

base="light"
primaryColor="#3F51B5"
backgroundColor="#fafafa"
secondaryBackgroundColor="#F0F2F6"
textColor="#232323"
font="sans serif"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"